[package]
name = "rodrigoRust"
version = "0.1.0"
authors = ["mrbianchi <marcelorbianchi96@gmail.com>"]
edition = "2018"

[dependencies]
"tiny-bip39" = "0.6.2"
"bitcoin" = "0.18.0"
"bip32" = "0.0.0"
"secp256k1" = "0.12.2"
"rayon" = "1.0.3"
"chrono" = "*"
"simplelog" = "*"
"log" = "*"